### ISSUE TITLE
Questionnaire Page | Refactor

### ISSUE THREAD

**Issue by Asmaathabet** [GSG-G7/shrinc#130]
- the questionnaire works even if you didn't select any choice in any question , it must be handled :-1:  . 
- the style , font size and container for every question is different from the other , it should be customized for all  :-1: . 
- when the user done from answering questionnaire , the message that appear in the Notification was not descriptive , it displays just 'done' 
I suggest to be more descriptive  for the user like 'Questionnaire done, you will direct for the suitable therapy'  
- question 9 [UN clickable ] and it takes the same value from question 10 :-1:  :-1:

**Comment by fadeomar** [comment]
that's a lot of point but thanks for alert me  :shipit:

**Comment by fadeomar** [comment]
you can try it now all fixed
