### ISSUE TITLE
Result Page Route | Refactor 

### ISSUE THREAD

**Issue by Asmaathabet** [GSG-G7/shrinc#132]
- when you wrote /result in the url , it displays the results page , and this is wrong , it shouldn't display the page by this way !!  
[ it should display only after Questionnaire submit answers ]

**Comment by fadeomar** [comment]
Good point :+1:

**Comment by fadeomar** [comment]
we will display to the user notification contain that "you have to solve the questionnaire "
and then we will redirect them to the  questionnaire page
