### ISSUE TITLE
Initialize the app

### ISSUE THREAD

**Issue by hashemt** [GSG-G7/shrinc#52]
Initialize the app and install the required modules

We will have two package.json one of them in the root folder and the other one in the client folder

File Structure  React #53 
File Structure Backend #60
Travis #49

## Server
devDependencies:
 * eslint  #50
 * nodemon
 * supertest
 * tap-spec
 * tape

dependencies:
* airtable
* cloudinary
 * yup
 * dotenv
 * express

## React
devDependencies:
 * eslint  #50
* pre-commit

dependencies:
* axios
* prop-types
* yup

**Comment by fadeomar** [comment]
Done :+1:
