### ISSUE TITLE
Questionnaire Draft

### ISSUE THREAD

**Issue by Oliversw** [GSG-G7/shrinc#8]
**NOTE: They were not able to finish all scores by today, and as they have noted, there is another category to be added.**
Because of this, I think that for the Figma, we should do the 4 approaches that are listed, and only the questions that already have scores (questions 1-5). If we can design it in a way that we can add the changes later, that would be ideal! Let me know what you think.

From Hanna and Max:

As you can see each question has scores that correspond to different therapy approaches:
CBT stands for cognitive behavioural therapy
PD stands for Psychodynamic Therapy
Hu stands for Humanistic psychotherapy
In stands for integrative psychotherapy 
C stands for counselling
STPD stands for Short Term Psychodynamic Psychotherapy

And I need to add ‘counselling’ as another category, and complete scores for all the questions which I can do by Wednesday or Thursday

A user would select all the options that seems appropriate and would have different scores corresponding to different therapy

As you can see each question provides different scores that indicate the correspondence of each answer to each different approach.

At the end of the questionnaire the client will have several scores (indicated at the end of each answer in brackets), corresponding to every approach, resulting from their answers. The approach where the client will have reached the highest score will be the recommended one, followed in order by the other ones.
For example, a client might have scored 65 in CBT, 32 in psychodynamic psychotherapy, 38 in Humanistic psychotherapy and 56 in counselling.This client should mostly look at CBT or counselling as the options that are likely to be suitable.

1. **What do you plan to achieve from therapy?**

Receiving guidance and strategies to solve my problems (CBT 5, PD 0, Hu 1, In 2, C 0, STPD 0)

Understanding my difficulties in relating to other people  (CBT 3, PD 4, Hu 4, In 4, C 0, STPD 0)

Changing my perspective on my difficulties  (CBT 2, PD 4, Hu 5, In 3, C 0, STPD 0)

Just having someone to talk to would help (CBT 1, PD 2, Hu 4, In 4, C 0, STPD 0)

Understanding parts of me that I am unaware of with the help of a therapist (CBT 0, PD 5, Hu 2, In 3, C 0, STPD 0)

2. **What do you look for in a therapist?** 

A professional who can give me good, impartial advice on my problems  (CBT 5, PD 1, Hu 2, In 3, C 0, STPD 0)

Someone who understands me truly (CBT 1, PD 3, Hu 4, In 4, C 0, STPD 0)

A reliable person who I can trust and confide in (CBT 1, PD 4, Hu 5, In 4, C 0, STPD 0)

Someone who can challenge me to resolve my interpersonal problems by showing me by blind spots (CBT 2, PD 5, Hu 1, In 3, C 0, STPD 0)

3. **What do you think is the root cause of your problems?**

I am generally happy but something happened recently that has completely thrown me (CBT 2, PD 3, Hu 4, In 4, C 0, STPD 0)

I have always thought I need to see a therapist but never got round to it. I have no idea where my problems stem from. (CBT 0, PD 4, Hu 4, In 5, C 0, STPD 0)

My main source of difficulties are my relationships, past and current (CBT 0, PD 5, Hu 4, In 4, C 0, STPD 0)

I have a general sense of dissatisfaction with many aspects of my life at present and do not know why (CBT 1, PD 5, Hu 5, In 4, C 0, STPD 0)

There is one specific area of my life that I would like to change and this is the cause of my problems (CBT 4, PD 3, Hu 4, In 5, C 0, STPD 0)

I think my difficulties originate in my upbringing, and my significant relationships growing up (CBT 0, PD 5, Hu 2, In 4, C 0, STPD 0)

4. **Are you happy to talk about your feelings?**

Yes, this is what I could come to therapy for (CBT 1, PD 5, Hu 5, In 4, C 0, STPD 0)

No, I find this really hard (CBT 4, PD 2, Hu 1, In 2, C 0, STPD 0)

Yes, although I find it challenging at times (CBT 3, PD 4, Hu 5, In 4, C 0, STPD 0)

No, I prefer thinking about problem solving than my feelings (CBT 5, PD 0, Hu 0, In 1, C 0, STPD 0)

5. **How long would you foresee seeing a therapist?**

Less than one month (CBT 5, PD 0, Hu 2, In 3, C 0, STPD 0)

2-4 month (CBT 25, PD 0, Hu 3, In 3, C 0, STP 25)

1 year ( CBT 2, PD 4, Hu 5, In 5, C 0, STP 1)

2-3 years (CBT 0, PD 15, Hu 10, In 10, C 0, STP 0)

6. My ideal therapist would be

Warm, understanding (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Knowledgeable, impartial (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Kind but straight to the point (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Eclectic, unconventional (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

7. I am someone who

Is deeply curious about oneself (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Wants to challenge one’s fears (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Likes to be in control (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Can become easily overwhelmed (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Does not want to dig too deep into painful matters (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Prefers to address the present than the past (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

Wants to find the root cause (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

8. Therapy for me is

A solution to a problem (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

An opportunity to transform (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

A lifeline (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

A journey into one’s mind (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

A source of unconditional support (CBT 0, PD 0, Hu 0, In 0, C 0, STP 0)

**Comment by Asmaathabet** [comment]
I think that there was a fifth approach that starts from the third question . what does it mean ? and can it added with its points to the first 2 questions ? in order to consider it as multiple choice as a Unified system .  for the rest of questions I think that we can consider them as select box .

**Comment by Oliversw** [comment]
@Asmaathabet I'm sorry, I never saw this notification! That's a good point though! I thought at first that some questions did not have points for everything but in some they have 0 points ... Very sorry again that I did not get this notification earlier! Will look into that now.

**Comment by Oliversw** [comment]
@AbdallahAmmar96 Max also sent this through for the scoring:
> Scoring system
As you can see each question provides different scores that indicate the correspondence of each answer to each different approach. 
At the end of the questionnaire the client will have several scores (indicated at the end of each answer in brackets), corresponding to every approach, resulting from their answers. The approach where the client will have reached the highest score will be the recommended one, followed in order by the other ones.
For example, a client might have scored 65 in CBT, 32 in psychodynamic psychotherapy, 38 in Humanistic psychotherapy and 56 in counselling.This client should mostly look at CBT or counselling as the options that are likely to be suitable.

This would mean that we would show the top suggestions for the types of therapy, followed by the others in order. Do you think that might be possible?

**Comment by Oliversw** [comment]
@AbdallahAmmar96 @Asmaathabet while we wait for the exact values to be finished, I have included a point value of 0 for everything that wasn't yet listed. I think it might be best that the questions and values are kept in something like e JSON file and accessed from there, so that the values can be changed and edited as needed. Will update you when I hear more!

**Comment by AbdallahAmmar96** [comment]
Hi Oliver,
Actually we make the same Scoring system you mention before,
 and we will add the suggestion as soon as possible, and all the questions and values already in a JSON file so it's easy to edit the data we we get it.
